<?php  //[STAMP] a8cf3c7461a512a056a510cd9f14df23
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\CodeHelper;
use Codeception\Module\Mockery;

trait CodeGuyActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
